##################################
############ BINDS ##############
#################################

#########################
###### BASIC BINDS ######
#########################
# shift selection using SUPER + Arrow
bind = Super, Left, movefocus, l # [hidden]
bind = Super, Right, movefocus, r # [hidden]
bind = Super, Up, movefocus, u # [hidden]
bind = Super, Down, movefocus, d # [hidden]

# shift window
bind = Super+Shift, Left, movewindow, l # [hidden]
bind = Super+Shift, Right, movewindow, r # [hidden]
bind = Super+Shift, Up, movewindow, u # [hidden]
bind = Super+Shift, Down, movewindow, d # [hidden]

# resize window
binde = Super, Minus, splitratio, -0.1 # [hidden]
binde = Super, Equal, splitratio, +0.1 # [hidden]
binde = Super, Semicolon, splitratio, -0.1 # [hidden]
binde = Super, Apostrophe, splitratio, +0.1 # [hidden]

# move with mouse
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

# floating mode
bind = Super+Alt, Space, togglefloating,

# fullscreens
bind = Super, F, fullscreen, 0
bind = Super, D, fullscreen, 1
bind = Super+Alt, F, fullscreenstate, 0 3 # Toggle fake fullscreen
bind = Super+Alt, D, fullscreenstate, 3 0 # Toggle fake anti fullscreen

# cycle windows
bind = Alt, Tab, cyclenext # [hidden] sus keybind
bind = Alt, Tab, bringactivetotop, # [hidden] bring it to the top



########################
###### WORKSPACES ######
########################
# Switching
# switch to next/prev workspace
bind = Ctrl+Super, Right, workspace, r+1 # [hidden]
bind = Ctrl+Super, Left, workspace, r-1 # [hidden]

# switch to workspace N
bind = Super, 1, workspace, 1 # [hidden]
bind = Super, 2, workspace, 2 # [hidden]
bind = Super, 3, workspace, 3 # [hidden]
bind = Super, 4, workspace, 4 # [hidden]
bind = Super, 5, workspace, 5 # [hidden]
bind = Super, 6, workspace, 6 # [hidden]
bind = Super, 7, workspace, 7 # [hidden]
bind = Super, 8, workspace, 8 # [hidden]
bind = Super, 9, workspace, 9 # [hidden]
bind = Super, 0, workspace, 10 # [hidden]

# switch to special workspace
bind = Super, S, togglespecialworkspace,

# Movement
# move window to next/prev workspace
bind = Ctrl+Super+Shift, Right, movetoworkspace, r+1 # [hidden]
bind = Ctrl+Super+Shift, Left, movetoworkspace, r-1 # [hidden]

# move window to N workspace
bind = Super+Shift, 1, movetoworkspacesilent, 1 # [hidden]
bind = Super+Shift, 2, movetoworkspacesilent, 2# [hidden]
bind = Super+Shift, 3, movetoworkspacesilent, 3 # [hidden]
bind = Super+Shift, 4, movetoworkspacesilent, 4 # [hidden]
bind = Super+Shift, 5, movetoworkspacesilent, 5 # [hidden]
bind = Super+Shift, 6, movetoworkspacesilent, 6 # [hidden]
bind = Super+Shift, 7, movetoworkspacesilent, 7 # [hidden]
bind = Super+Shift, 8, movetoworkspacesilent, 8 # [hidden]
bind = Super+Shift, 9, movetoworkspacesilent, 9 # [hidden]
bind = Super+Shift, 0, movetoworkspacesilent, 10 # [hidden]

# move window to special workspace
bind = Super+Shift, S, movetoworkspacesilent, special

# Essential other
# kill  window
bind = Super, Q, killactive,
bind = Super, W, exec, librewolf
bind = Super, X, layoutmsg, togglesplit
bind = Super, Z, exec, zeditor
bind = Super, P, pin
bind = Super, C, exec, cd $HOME/nixos-config-rewrite ; nix develop --command zeditor .
bind = Super, T, exec, kitty
