font=Comfortaa:size=17
terminal=kitty -e
# prompt="> "
layer=overlay
lines=8
width=24
# dpi-aware=yes
inner-pad=16
horizontal-pad=16
vertical-pad=16
# match-counter=yes
# use-bold=true
icon-theme="Papirus"
include=~/.cache/matugen/fuzzel.ini
# anchor=left
anchor=top-left
x-margin = 13
y-margin = 13
letter-spacing = 1
# hide-before-typing = true

[border]
radius=10
width=3
selection-radius=4

