[config]
version_check = false

fallback_color = "#000000"

expr_prefix = "{{"
expr_postfix = "}}"

block_prefix = "<*"
block_postfix = "*>"

[templates.quickshell]
input_path = "./quickshell.qml"
output_path = "~/.cache/matugen/quickshell/Colors_gen.qml"

[templates.helix]
input_path = "./helix.toml"
output_path = "~/.config/helix/themes/matugen-theme.toml"
post_hook = "pkill hx --signal SIGUSR1"

[templates.kitty]
input_path = './kitty.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --config-file-name=themes.conf --reload-in=all Matugen && pkill kitty --signal SIGUSR1"

[templates.niri]
input_path = './niri.kdl'
output_path = '~/.cache/matugen/niri/colors.kdl'

[templates.fuzzel]
input_path = './fuzzel.ini'
output_path = '~/.cache/matugen/fuzzel.ini'

[templates.gtk3]
input_path = './gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = './gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
